spring:
  application:
    name: lovable-clone

  # Virtual thread Configurations
  threads:
    virtual:
      enabled: true

  # PostgresSQL Database Connection Settings
  datasource:
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate Configurations
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        #format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
